# Using Piper general purpose pipeline for Azure

trigger:
  - develop

schedules:
  - cron: "0 0 * * *"
    displayName: pipeline optimization
    always: true # whether to always run the pipeline or only if there have been source code changes since the last successful scheduled run. The default is false.
    branches:
      include:
        - develop

resources:
  repositories:
  - repository: piper-pipeline-azure
    endpoint: github.tools.sap
    type: githubenterprise
    name: tua-spa-organization/piper-pipeline-azure

extends:
  template: sap-piper-pipeline.yml@piper-pipeline-azure
  